#!/bin/sh

function usage {
  echo "Usage: $0 <docker tag>"
}
[ -z "$1" ] && usage && exit 1

tag="$1"

x() {
    n=$(basename "$1")
    [ -f "$n" ] && echo "$n already fetched" || wget "$1"
}
x http://ftp.gnu.org/gnu/binutils/binutils-2.33.1.tar.gz
x http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz
x http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/ISO-IMAGES/11.1/FreeBSD-11.1-RELEASE-amd64-dvd1.iso
x http://ftp.gnu.org/gnu/mpfr/mpfr-4.0.2.tar.xz
x http://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
x http://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz

S=$(sha256sum FreeBSD-11.1-RELEASE-amd64-dvd1.iso | awk '{print $1}')
if [ "$S" != "49e8f32e0a097a1ab411cb85f1adf6d78ba931ff557a07cd1e84af62a47c2d6f" ]
then
    >&2 echo "Error: sha256sum does not match"
    exit 1
fi
mkdir -p freebsd
(cd freebsd; 7z x ../FreeBSD-11.1-RELEASE-amd64-dvd1.iso usr/include)
(cd freebsd; 7z x ../FreeBSD-11.1-RELEASE-amd64-dvd1.iso usr/lib)
(cd freebsd; 7z x ../FreeBSD-11.1-RELEASE-amd64-dvd1.iso lib)

docker build -t $tag .
exit 0
